// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPNALmfJqBAmFcHbkibEFTqgkKSepS8A',
    appId: '1:731410719736:web:4bc8b99a3f766cd0552c0d',
    messagingSenderId: '731410719736',
    projectId: 'bmi-tracker-89be6',
    authDomain: 'bmi-tracker-89be6.firebaseapp.com',
    storageBucket: 'bmi-tracker-89be6.firebasestorage.app',
    measurementId: 'G-N7KFCJ99X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLWcJv_zKdGuy0SEv_0FifAOvFjXhlN4',
    appId: '1:731410719736:android:3bbe54eb49d7df9a552c0d',
    messagingSenderId: '731410719736',
    projectId: 'bmi-tracker-89be6',
    storageBucket: 'bmi-tracker-89be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdS0lu3yylpdo3RbjB2g6tLJgYarHiLI',
    appId: '1:731410719736:ios:4a3d0b9d6734c91c552c0d',
    messagingSenderId: '731410719736',
    projectId: 'bmi-tracker-89be6',
    storageBucket: 'bmi-tracker-89be6.firebasestorage.app',
    iosClientId: '731410719736-shg4kblnmoue0vjkkat8qihehtl2477q.apps.googleusercontent.com',
    iosBundleId: 'com.vitalis.app.vitalis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdS0lu3yylpdo3RbjB2g6tLJgYarHiLI',
    appId: '1:731410719736:ios:4a3d0b9d6734c91c552c0d',
    messagingSenderId: '731410719736',
    projectId: 'bmi-tracker-89be6',
    storageBucket: 'bmi-tracker-89be6.firebasestorage.app',
    iosClientId: '731410719736-shg4kblnmoue0vjkkat8qihehtl2477q.apps.googleusercontent.com',
    iosBundleId: 'com.vitalis.app.vitalis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIPNALmfJqBAmFcHbkibEFTqgkKSepS8A',
    appId: '1:731410719736:web:a4a1daf69ef4125f552c0d',
    messagingSenderId: '731410719736',
    projectId: 'bmi-tracker-89be6',
    authDomain: 'bmi-tracker-89be6.firebaseapp.com',
    storageBucket: 'bmi-tracker-89be6.firebasestorage.app',
    measurementId: 'G-YF8HQK9EHN',
  );
}
